const API='https://wilds.mhdb.io/ja';
const W={armor:[],armorSets:[],weapons:[],skills:[],decorations:[],charms:[],targets:[],setTargets:[],groupTargets:[],loaded:false};
const $=id=>document.getElementById(id);
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const PARTS=['head','chest','arms','waist','legs'];
const PART_LABEL={head:'頭',chest:'胴',arms:'腕',waist:'腰',legs:'脚'};
function skillMaxLevel(skill){const levels=(skill?.ranks||[]).map(r=>Number(r.level)||0).filter(Boolean);return levels.length?Math.max(...levels):1;}
function levelOptions(max,current=1){return Array.from({length:max},(_,n)=>{const v=n+1;return `<option value="${v}" ${v===Number(current)?'selected':''}>Lv${v}</option>`;}).join('');}
function skillSearchText(skill){const local=(window.WILDS_SKILL_DETAILS||{})[norm(skill?.name)]||{};const parts=[skill?.name,skill?.description,local.description,...(local.levels||[]).flatMap(r=>[r?.effect,r?.description,r?.text])];for(const r of (skill?.ranks||[]))parts.push(r?.description,r?.effect,r?.text);return norm(parts.filter(Boolean).join(' ')).toLocaleLowerCase('ja');}
function setGroupRequired(skill,level){const r=(skill?.ranks||[]).find(x=>Number(x.level)===Number(level));return Number(r?.setPiecesRequired)||null;}
function makeSkillPicker(containerId,kind,targets,addFn){const p=$(containerId);p.innerHTML='';const usable=W.skills.filter(x=>x&&(kind==='normal'?(x.kind==='armor'||x.kind==='weapon'):x.kind===kind));const search=document.createElement('input');search.type='search';search.placeholder='スキル名・効果で検索…';search.autocomplete='off';const sel=document.createElement('select');const lv=document.createElement('select');const b=document.createElement('button');b.textContent='＋追加';function sync(){const sk=usable.find(x=>String(x.id)===String(sel.value));const max=skillMaxLevel(sk);lv.innerHTML=levelOptions(max,Math.min(Number(lv.value)||1,max));}
 function populate(filter=''){const q=norm(filter).toLocaleLowerCase('ja');const list=q?usable.filter(x=>skillSearchText(x).includes(q)):usable;const prev=sel.value;sel.innerHTML='<option value="">スキルを選択…</option>'+list.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(list.some(x=>String(x.id)===String(prev)))sel.value=prev;sync();}
 sel.onchange=sync;search.oninput=()=>populate(search.value);b.onclick=()=>{const id=+sel.value;if(!id)return;const sk=usable.find(x=>x.id===id);const level=Math.min(Number(lv.value)||1,skillMaxLevel(sk));addFn({id,name:sk.name,level});};p.append(search,sel,lv,b);populate();}
function renderPickers(){makeSkillPicker('normalSkillPicker','normal',W.targets,t=>{upsertTarget(W.targets,t);renderTargets();save();});makeSkillPicker('setSkillPicker','set',W.setTargets,t=>{upsertTarget(W.setTargets,t);renderTargets();save();});makeSkillPicker('groupSkillPicker','group',W.groupTargets,t=>{upsertTarget(W.groupTargets,t);renderTargets();save();});}
function upsertTarget(arr,t){const x=arr.find(v=>v.id===t.id);if(x)x.level=t.level;else arr.push(t);}
function renderTargetRows(id,arr,kind){const d=$(id);d.innerHTML=arr.map((t,i)=>{const sk=W.skills.find(x=>x.id===t.id);const max=skillMaxLevel(sk);const level=Math.min(Number(t.level)||1,max);t.level=level;const req=kind==='set'||kind==='group'?setGroupRequired(sk,level):null;const info=wildsSkillInfo(t.name);const levels=(info.levels||[]).filter(x=>x.level===level);return `<div class="selected-skill"><b>${esc(t.name)}</b><select data-i="${i}" class="targetLv">${levelOptions(max,level)}</select>${req?`<span class="small">${req}部位</span>`:''}${MHSkillPopover.button(t.name,{...info,levels})}<button data-i="${i}" class="removeTarget">削除</button></div>`;}).join('');d.querySelectorAll('.targetLv').forEach(e=>e.onchange=()=>{arr[+e.dataset.i].level=+e.value;renderTargets();save();});d.querySelectorAll('.removeTarget').forEach(e=>e.onclick=()=>{arr.splice(+e.dataset.i,1);renderTargets();save();});}
function renderTargets(){renderTargetRows('selectedNormalSkills',W.targets,'normal');renderTargetRows('selectedSetSkills',W.setTargets,'set');renderTargetRows('selectedGroupSkills',W.groupTargets,'group');}
function itemSkills(item){const m=new Map();for(const x of (item?.skills||[])){const k=norm(x.skill?.name);if(k)m.set(k,(m.get(k)||0)+(Number(x.level)||0));}return m;}
function mergeMaps(arr){const m=new Map();for(const x of arr)for(const [k,v] of x)m.set(k,(m.get(k)||0)+v);return m;}
function slots(item){return (item?.slots||[]).map(Number).filter(Boolean).sort((a,b)=>b-a);}
function fitsDecoration(slot,d){return Number(d.slot)<=slot;}
function uniqueSkillNames(targets){return [...new Set(targets.map(t=>norm(t.name)))];}
function scoreItem(item,targets){const m=itemSkills(item);let sat=0;for(const t of targets)sat+=Math.min(Number(t.level)||0,m.get(norm(t.name))||0);return sat;}
function flattenCharms(){const out=[{id:'none',name:'護石なし',skills:[],source:null}];for(const c of W.charms){if(c?.randomized)continue;for(const r of (c.ranks||[])){if(!(r.skills||[]).length)continue;out.push({id:`${c.id}:${r.id}`,name:r.name||c.name||`護石${c.id}`,skills:r.skills,source:c,rank:r});}}return out;}
function armorSetMeta(a){return a?.armorSet||null;}
function bonusSkillForArmor(a,kind){const s=armorSetMeta(a)?.[kind==='set'?'setBonusSkill':'groupBonusSkill'];return s||null;}
function armorBonusSatisfied(set,targets){const out={set:new Map(),group:new Map()};for(const t of targets){const sk=W.skills.find(x=>x.id===t.id);const key=norm(t.name);let pieces=0;if(t.kind==='set'){const bySet=new Map();for(const a of set){const meta=armorSetMeta(a);const bonus=bonusSkillForArmor(a,'set');if(norm(bonus?.name)===key){const sid=meta?.id??meta?.gameId??meta?.name;const k=String(sid);bySet.set(k,(bySet.get(k)||0)+1);}}pieces=Math.max(0,...bySet.values());}else{for(const a of set){const bonus=bonusSkillForArmor(a,'group');if(norm(bonus?.name)===key)pieces++;}}const req=setGroupRequired(sk,t.level);out[t.kind].set(key,pieces);if(!req||pieces<req)return false;}return true;}
function armorKey(a){const meta=armorSetMeta(a);return `${a.kind}:${meta?.gameId??meta?.id??meta?.name??a.name}`;}
function armorCandidates(){const byKind={};for(const p of PARTS)byKind[p]=W.armor.filter(a=>a?.kind===p);let beams=[{set:[],skills:new Map(),slots:[]}];const normal=W.targets;for(const p of PARTS){const bonusNames=new Set([...W.setTargets,...W.groupTargets].map(t=>norm(t.name)));const basePool=byKind[p].slice().sort((a,b)=>{const sa=scoreItem(a,normal),sb=scoreItem(b,normal);return sb-sa || slots(b).reduce((x,y)=>x+y,0)-slots(a).reduce((x,y)=>x+y,0);}).slice(0,100);const bonusPool=byKind[p].filter(a=>{const bs=[bonusSkillForArmor(a,'set'),bonusSkillForArmor(a,'group')].map(x=>norm(x?.name));return bs.some(n=>bonusNames.has(n));});const pool=[...new Map([...basePool,...bonusPool].map(a=>[armorKey(a),a])).values()];const next=[];for(const st of beams)for(const a of pool){const ms=mergeMaps([st.skills,itemSkills(a)]);next.push({set:[...st.set,a],skills:ms,slots:[...st.slots,...slots(a)]});}next.sort((a,b)=>{const sa=normal.reduce((s,t)=>s+Math.min(t.level,a.skills.get(norm(t.name))||0),0);const sb=normal.reduce((s,t)=>s+Math.min(t.level,b.skills.get(norm(t.name))||0),0);return sb-sa||b.slots.reduce((x,y)=>x+y,0)-a.slots.reduce((x,y)=>x+y,0);});beams=next.slice(0,800);}
return beams.filter(st=>armorBonusSatisfied(st.set,W.setTargets.map(t=>({...t,kind:'set'})))&&armorBonusSatisfied(st.set,W.groupTargets.map(t=>({...t,kind:'group'}))));}
function decorationPool(kind){return W.decorations.filter(d=>d?.kind===kind);}
function fillDecorations(weaponSlots,armorSlots,baseSkills){const deficits=W.targets.map(t=>({name:norm(t.name),need:Math.max(0,Number(t.level)-(baseSkills.get(norm(t.name))||0))})).filter(x=>x.need>0);const used=[];const ws=[...weaponSlots],as=[...armorSlots];const pools={weapon:decorationPool('weapon'),armor:decorationPool('armor')};const sortedTargets=[...deficits].sort((a,b)=>b.need-a.need);for(const target of sortedTargets){let need=target.need;for(const kind of ['weapon','armor']){const arr=kind==='weapon'?ws:as;const ds=pools[kind].filter(d=>(d.skills||[]).some(s=>norm(s.skill?.name)===target.name)).sort((a,b)=>Number(b.slot)-Number(a.slot));while(need>0){let found=null,idx=-1;for(let i=0;i<arr.length;i++){const d=ds.find(x=>fitsDecoration(arr[i],x));if(d){found=d;idx=i;break;}}if(!found)break;const gain=Math.max(...found.skills.filter(s=>norm(s.skill?.name)===target.name).map(s=>Number(s.level)||0));used.push({name:found.name,slot:found.slot,kind,skill:target.name,level:gain});arr.splice(idx,1);need-=gain;}}}
const rem=deficits.map(x=>({name:x.name,need:Math.max(0,x.need-used.filter(u=>u.skill===x.name).reduce((s,u)=>s+u.level,0))})).filter(x=>x.need>0);return {used,remaining:rem,weaponLeft:ws,armorLeft:as};}
function activeSkillMap(weapon,armor,charm,decos){const maps=[itemSkills(weapon),...armor.map(itemSkills),itemSkills(charm)];for(const d of decos){maps.push(itemSkills(d));}return mergeMaps(maps);}
function evaluateCombo(weapon,armor,charm){const base=mergeMaps([itemSkills(weapon),...armor.map(itemSkills),itemSkills(charm)]);const deco=fillDecorations(slots(weapon),armor.flatMap(slots),base);const final=activeSkillMap(weapon,armor,charm,deco.used.map(u=>W.decorations.find(d=>d.name===u.name&&d.kind===u.kind&&Number(d.slot)===Number(u.slot))||{skills:[{skill:{name:u.skill},level:u.level}]}));const rem=W.targets.map(t=>({name:norm(t.name),need:Math.max(0,Number(t.level)-(final.get(norm(t.name))||0))})).filter(x=>x.need>0);const sat=W.targets.reduce((s,t)=>s+Math.min(Number(t.level),final.get(norm(t.name))||0),0);return {weapon,armor,charm,decos:deco.used,remaining:rem,skills:final,sat,total:W.targets.reduce((s,t)=>s+Number(t.level),0),slotScore:deco.weaponLeft.reduce((s,x)=>s+x,0)+deco.armorLeft.reduce((s,x)=>s+x,0)};}
function makeCandidates(){const armorStates=armorCandidates();const charms=flattenCharms();const targetNames=uniqueSkillNames(W.targets);const weaponPool=W.weapons.filter(w=>w).map(w=>({w,score:scoreItem(w,W.targets),slots:slots(w).reduce((s,x)=>s+x,0)})).sort((a,b)=>b.score-a.score||b.slots-a.slots).slice(0,500).map(x=>x.w);const charmPool=charms.map(c=>({c,score:scoreItem(c,W.targets)})).sort((a,b)=>b.score-a.score).slice(0,150).map(x=>x.c);const wc=[];for(const w of weaponPool)for(const c of charmPool){const s=scoreItem(w,W.targets)+scoreItem(c,W.targets);wc.push({w,c,s,slots:slots(w).reduce((a,b)=>a+b,0)});}wc.sort((a,b)=>b.s-a.s||b.slots-a.slots);const weaponCharmPairs=wc.slice(0,3000);const out=[];for(const st of armorStates){for(const pair of weaponCharmPairs){const c=evaluateCombo(pair.w,st.set,pair.c);if(c.sat===c.total)out.push(c);else if(out.length<10)out.push(c);}}out.sort((a,b)=>(b.sat-b.total)-(a.sat-a.total)||b.sat-a.sat||b.slotScore-a.slotScore);return out.slice(0,30);}
function wildsSkillInfo(name){const sk=W.skills.find(x=>norm(x.name)===norm(name));const local=(window.WILDS_SKILL_DETAILS||{})[norm(name)]||{};const description=local.description||sk?.description||'';if(!sk)return {name,description,levels:local.levels||[]};const ranks=(sk.ranks||[]).map(r=>({level:Number(r.level)||0,effect:r.description||r.effect||r.text||''})).filter(x=>x.level&&x.effect);if(ranks.length){const localByLevel=new Map((local.levels||[]).map(x=>[Number(x.level),x.effect]));return {name,description,levels:ranks.map(x=>localByLevel.has(x.level)?{...x,effect:localByLevel.get(x.level)}:x)};}return {name,description,levels:description?[{level:1,effect:description}]:[]};}
function allActiveSkills(c){const m=new Map();for(const x of [c.weapon,c.charm,...c.armor])for(const s of (x?.skills||[])){const n=norm(s.skill?.name);if(n)m.set(n,(m.get(n)||0)+(Number(s.level)||0));}for(const d of c.decos)for(const s of (d.skills||[])){const n=norm(s.skill?.name);if(n)m.set(n,(m.get(n)||0)+(Number(s.level)||0));}for(const t of W.setTargets){if(setGroupRequired(W.skills.find(s=>s.id===t.id),t.level))m.set(t.name,Math.max(m.get(t.name)||0,t.level));}for(const t of W.groupTargets){if(setGroupRequired(W.skills.find(s=>s.id===t.id),t.level))m.set(t.name,Math.max(m.get(t.name)||0,t.level));}return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0],'ja'));}
function renderAllActiveSkills(c){const list=allActiveSkills(c);return `<details open class="active-skills"><summary>発動スキル（${list.length}種）</summary><div class="skill-list">${list.map(([name,lv])=>`<div class="active-skill-line"><span>${esc(name)} Lv${lv}</span>${MHSkillPopover.button(name,wildsSkillInfo(name))}</div>`).join('')}</div></details>`;}
function renderResults(cands){const r=$('results');if(!cands.length){$('status').classList.remove('hidden');$('status').textContent='候補なし';r.innerHTML='';return;}$('status').classList.add('hidden');r.innerHTML=cands.map((c,i)=>`<section class="card result"><h3>#${i+1} 目標充足 ${c.sat}/${c.total}</h3><div><b>武器:</b> ${esc(c.weapon.name)}</div>${c.charm?.source?`<div><b>護石:</b> ${esc(c.charm.name)}</div>`:'<div><b>護石:</b> なし</div>'}<div>${c.armor.map(a=>`<div>${PART_LABEL[a.kind]||a.kind}: ${esc(a.name)}</div>`).join('')}</div>${renderAllActiveSkills(c)}<div class="small">装飾品: ${c.decos.length?c.decos.map(d=>`${esc(d.name)}×1`).join(' / '):'なし'}</div>${c.remaining.length?`<div class="warn">目標不足: ${c.remaining.map(x=>esc(x.name)+' Lv'+x.need).join(' / ')}</div>`:'<div class="ok">目標スキル充足</div>'}</section>`).join('');}
async function fetchJSON(path){const r=await fetch(API+path);if(!r.ok)throw new Error(`${path} HTTP ${r.status}`);return r.json();}
async function loadDB(){try{const [armor,armorSets,weapons,skills,deco,charms]=await Promise.all(['/armor','/armor/sets','/weapons','/skills','/decorations','/charms'].map(fetchJSON));W.armor=armor;W.armorSets=armorSets;W.weapons=weapons;W.skills=skills;W.decorations=deco;W.charms=charms;W.loaded=true;$('dbVersion').textContent=`Wilds 日本語DB loaded / Armor ${armor.length} / Weapons ${weapons.length} / Skills ${skills.length} / Decorations ${deco.length} / Charms ${charms.length}`;renderPickers();$('solveBtn').disabled=false;$('solveBtn').textContent='検索する';const saved=MHStorage.load('wilds');if(saved?.data)restore(saved.data);}catch(e){$('dbVersion').textContent='Wilds 日本語DBの読み込みに失敗しました';$('status').classList.remove('hidden');$('status').textContent='DB接続エラー: '+e.message;}}
function stateData(){return {targets:W.targets,setTargets:W.setTargets,groupTargets:W.groupTargets};}
function save(){MHStorage.save('wilds',stateData());}
function restore(d){W.targets=d.targets||[];W.setTargets=d.setTargets||[];W.groupTargets=d.groupTargets||[];renderTargets();}
$('solveBtn').onclick=async()=>{if(!W.loaded||(!W.targets.length&&!W.setTargets.length&&!W.groupTargets.length)){ $('status').classList.remove('hidden');$('status').textContent='目標スキルを1つ以上選択してください。';return;}MHSearchUI.start();await new Promise(r=>setTimeout(r,20));MHSearchUI.step('②','防具構成を探索中',30);const c=makeCandidates();MHSearchUI.step('③','武器・護石・装飾品を評価中',80);renderResults(c);save();MHSearchUI.done();};
$('saveBtn').onclick=save;$('loadBtn').onclick=()=>{const x=MHStorage.load('wilds');if(x?.data)restore(x.data);};$('clearSaveBtn').onclick=()=>{MHStorage.clear('wilds');W.targets=[];W.setTargets=[];W.groupTargets=[];renderTargets();};
loadDB();
