const $=id=>document.getElementById(id);const state={db:null};
const TARGETS=[['属性攻撃強化','elementalAttack',5],['弱点特効【属性】','elementalWeakness',3],['龍気変換','dragonConversion',3],['激昂','furious',3],['鋼殻の恩恵','steelBlessing',3],['伏魔響命','dereliction',3],['砲弾装填','loadShells',2],['冰気錬成','frostcraft',3],['ガード強化','guardUp',1],['煽衛','embolden',3],['回避距離','evadeExtender',3]];
const alias={"回避距離":"回避距離ＵＰ","属性攻撃強化":"属性攻撃強化","弱点特効【属性】":"弱点特効cite属性","冰気錬成":"冰気錬成","鋼殻の恩恵":"鋼殻の恩恵","伏魔響命":"伏魔響命","龍気変換":"龍気変換","激昂":"激昂","砲弾装填":"砲弾装填","ガード強化":"ガード強化","煽衛":"煽衛"};
function norm(s){return (s||'').replace(/cite[^]*/g,'').replace(/ＵＰ/g,'UP').replace(/ /g,'').trim()}
function keyFor(s){let n=norm(s);if(n==='回避距離UP')return 'evadeExtender';if(n==='弱点特効属性')return 'elementalWeakness';const m={'属性攻撃強化':'elementalAttack','龍気変換':'dragonConversion','激昂':'furious','鋼殻の恩恵':'steelBlessing','伏魔響命':'dereliction','砲弾装填':'loadShells','冰気錬成':'frostcraft','ガード強化':'guardUp','煽衛':'embolden'};return m[n]||n}
TARGETS.forEach(([name,id,max])=>{$('skills').insertAdjacentHTML('beforeend',`<div class="skill"><span>${name}</span><input id="${id}" type="number" min="0" max="${max}" value="${max}"></div>`)});
function armorRow(row,part){const s={};for(let i=1;i<=5;i++){const k=row['スキル系統'+i],v=+(row['スキル値'+i]||0);if(k&&v)s[keyFor(k)]=(s[keyFor(k)]||0)+v}return {part,name:row['名前'],slots:[+row['スロット1']||0,+row['スロット2']||0,+row['スロット3']||0].filter(x=>x>0),rarity:+row['レア度']||0,skills:s}}
function targets(){const t={};TARGETS.forEach(([n,id])=>t[id]=+$(''+id).value||0);return t}
function merge(a,b){const o={...a};for(const[k,v]of Object.entries(b))o[k]=(o[k]||0)+v;return o}
function enoughPossible(cur, remaining, t, maxRemaining){for(const k of Object.keys(t))if((cur[k]||0)+(maxRemaining[k]||0)<t[k])return false;return true}
function makeDecos(db){return db.decorations.map(r=>{const k=keyFor(r['スキル系統1']);return {name:r['名前'],size:+r['スロットサイズ']||0,skill:k,value:+r['スキル値1']||0}}).filter(d=>d.size&&d.skill&&d.value)}
function fillDecos(slots,need,decos){const ds=Object.values(need).some(v=>v>0)?decos:[];const keys=Object.keys(need).filter(k=>need[k]>0);const usable=ds.filter(d=>keys.includes(d.skill)).sort((a,b)=>(b.value/a.size)-(a.value/b.size)||b.value-a.value);const slots2=[...slots].sort((a,b)=>b-a);const res=[],left={...need};for(const slot of slots2){let best=null;for(const d of usable){if(d.size<=slot&&left[d.skill]>0&&(!best||d.value>best.value||(d.value===best.value&&d.size<best.size)))best=d}if(best){res.push(best);left[best.skill]=Math.max(0,left[best.skill]-best.value)}}return Object.values(left).every(v=>v<=0)?res:null}
function solve(){if(!state.db)return;const t=targets();const parts=[['頭',state.db.head],['胴',state.db.chest],['腕',state.db.arms],['腰',state.db.waist],['脚',state.db.legs]];const end=$('tier').value==='mr';const pools=parts.map(([p,rows])=>rows.map(r=>armorRow(r,p)).filter(a=>!end||a.rarity>=8));const maxRemain=[];let acc={};for(let i=pools.length-1;i>=0;i--){for(const a of pools[i])acc=merge(acc,a.skills);maxRemain[i]=acc}const results=[];let nodes=0;function dfs(i,chosen,skills,slots){nodes++;if(results.length>=+$('limit').value)return;if(i===pools.length){const need={};for(const k of Object.keys(t))need[k]=Math.max(0,t[k]-(skills[k]||0));const deco=fillDecos(slots,need,makeDecos(state.db));if(deco){results.push({chosen:[...chosen],skills:{...skills},slots:[...slots],deco})}return}for(const a of pools[i]){const ns=merge(skills,a.skills);if(!enoughPossible(ns,pools.length-i-1,t,maxRemain[i+1]||{}))continue;dfs(i+1,[...chosen,a],ns,[...slots,...a.slots])}}dfs(0,[],{},[]);render(results,t,nodes,pools)}
function render(results,t,nodes,pools){$('status').className='card '+(results.length?'ok':'warn');$('status').innerHTML=`<b>${results.length?'候補を検出しました':'条件を満たす候補が見つかりません'}</b><p class="small">探索ノード: ${nodes.toLocaleString()} / 防具候補: ${pools.map(x=>x.length).join(' / ')}</p>`;$('status').classList.remove('hidden');if(!results.length){$('results').innerHTML='';return}$('results').innerHTML=results.map((r,i)=>`<section class="card result"><h2>候補 #${i+1}</h2><div class="grid">${r.chosen.map(a=>`<div class="piece"><b>${a.part}</b> ${a.name}<br><span class="small">スロット ${a.slots.join('-')||'なし'}</span></div>`).join('')}</div><h3>装飾品</h3>${r.deco.map(d=>`<span class="tag">${d.name} / ${d.skill} +${d.value}</span>`).join('')||'なし'}<h3>残り条件</h3><div>${Object.entries(t).map(([k,v])=>`<span class="tag">${k}: ${Math.min(v,r.skills[k]||0)}/${v}</span>`).join('')}</div><p class="small">※護石・傀異錬成はまだ自動生成せず、まず防具＋装飾品の合法候補を返します。</p></section>`).join('')}
$('solveBtn').onclick=solve;$('resetBtn').onclick=()=>location.reload();
(async()=>{try{const db=await MHRSBLibrary.all((k,n)=>{$('loadState').innerHTML=`<span class="spinner"></span> ${k} 読み込み完了（${n}件）`});state.db=db;$('loadState').textContent='データベース読み込み完了';$('loadState').className='loading ok';$('solveBtn').disabled=false}catch(e){$('loadState').textContent='データベースの読み込みに失敗しました: '+e.message;$('loadState').className='loading err'}})();